name: Run Parallel Jobs
on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  parallel-execution:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-index: ${{ fromJson('["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]') }}
        include:
          - os: ubuntu-latest
            node-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          - os: windows-latest
            node-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
          - os: macos-latest
            node-index: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install cloudscraper request randomstring
          
      - name: Run Node script with parameters
        run: |
          node m.js https://rapidis.gay/7778079525-ac6f591a-4fd1-4d9b-9748-9d3122f7d804 300 2 h1 ${{ matrix.node-index }} h1
          
